services:
  estoolkit:
    image: estoolkit
    build:
      context: frontend/node_modules/es-toolkit
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
