const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const faqs = [
  // ─── General Information ──────────────────────────────────────────────────
  { category: "General Information", question: "What is Techwell?", answer: "Techwell is a technology-focused company that offers business consulting, IT training and certification programmes, career guidance, campus hiring solutions, recruitment services, and job assistance. We help students, graduates, and professionals build meaningful careers in technology.", order: 10 },
  { category: "General Information", question: "How can I contact Techwell?", answer: "You can reach us through our official website contact form, by email at support@techwell.co.in, or by calling our support line during business hours (Monday–Saturday, 9 AM–6 PM IST). We aim to respond within 24 business hours.", order: 20 },
  { category: "General Information", question: "How do I register for a service?", answer: "Visit the Techwell website and use the relevant enquiry, registration, or application option for the service you need — such as course enrolment, job application, or campus hiring. Follow the on-screen steps to complete your registration.", order: 30 },
  { category: "General Information", question: "Where are Techwell's offices located?", answer: "Techwell operates primarily online and serves students and clients across India. Physical office or training-centre details, where applicable, are listed on the official website. Contact support for location-specific information.", order: 40 },
  { category: "General Information", question: "Is Techwell a registered company?", answer: "Yes. Techwell is a duly registered business entity. For formal verification or legal correspondence, please contact us at support@techwell.co.in.", order: 50 },
  { category: "General Information", question: "What makes Techwell different from other training providers?", answer: "Techwell combines technology training, AI-powered interview practice, live career guidance, direct industry connections, campus hiring partnerships, and recruitment support in a single integrated platform — helping candidates go from learning to employment efficiently.", order: 60 },
  { category: "General Information", question: "Does Techwell have a mobile app?", answer: "Techwell's platform is accessible via any modern web browser on desktop and mobile devices. Information about dedicated mobile apps, if and when available, will be published on the official website.", order: 70 },
  { category: "General Information", question: "Can I trust communications I receive from Techwell?", answer: "All official Techwell communications come from verified @techwell.co.in email addresses. If you receive a suspicious message claiming to be from Techwell, verify it through support@techwell.co.in before acting on it.", order: 80 },

  // ─── Training Courses ─────────────────────────────────────────────────────
  { category: "Training Courses", question: "What IT courses does Techwell offer?", answer: "Techwell offers courses in Networking, IT Support, Cloud Computing, DevOps, Cyber Security, Application Security, VAPT (Vulnerability Assessment & Penetration Testing), Endpoint Management, Artificial Intelligence, Software Development, Database Management, and more. The full catalogue is available on the Courses page.", order: 90 },
  { category: "Training Courses", question: "Are the courses suitable for beginners (freshers)?", answer: "Many Techwell courses are designed for beginners with no prior experience. Each course page clearly states the eligibility criteria, prerequisites, and target audience. Check the individual course listing to confirm suitability.", order: 100 },
  { category: "Training Courses", question: "Do you offer online training?", answer: "Yes. Techwell offers online training for most courses. Depending on the course and current availability, formats may include live online classes, recorded video sessions, or blended learning. Check the specific course page for the available mode of delivery.", order: 110 },
  { category: "Training Courses", question: "How long do the courses take to complete?", answer: "Course duration varies — ranging from a few weeks for short skill-specific courses to several months for comprehensive certification programmes. The expected duration is listed on each course's detail page.", order: 120 },
  { category: "Training Courses", question: "Are Techwell courses accredited or industry-recognised?", answer: "Several Techwell training programmes align with or prepare you for globally recognised industry certifications (e.g., CompTIA, Microsoft, AWS, EC-Council). Accreditation details, where applicable, are mentioned on each course page.", order: 130 },
  { category: "Training Courses", question: "Can I access course materials after the training ends?", answer: "Access to course materials after training completion depends on the specific course and plan purchased. Details about post-training access are outlined in the course description and in your enrolment agreement.", order: 140 },
  { category: "Training Courses", question: "What happens if I miss a live class session?", answer: "For live-session courses, recorded replays may be provided, subject to the course policy. Contact your course coordinator or support@techwell.co.in for information about a specific course.", order: 150 },
  { category: "Training Courses", question: "Is there a free trial or demo class available?", answer: "Some courses may offer a free demo or introductory session. Check the relevant course page or contact us at support@techwell.co.in to enquire about demo availability.", order: 160 },
  { category: "Training Courses", question: "Do you provide group or corporate training?", answer: "Yes. Techwell offers group and corporate training packages for organisations seeking to upskill their teams. Contact us at support@techwell.co.in or use the Consultancy enquiry form on the website.", order: 170 },

  // ─── Jobs ─────────────────────────────────────────────────────────────────
  { category: "Jobs", question: "Does Techwell provide jobs?", answer: "Techwell provides job assistance, career guidance, and recruitment-related services that connect candidates with employers. However, the final hiring decision — including selection, salary, and designation — rests solely with the employer.", order: 180 },
  { category: "Jobs", question: "Does Techwell guarantee employment?", answer: "No. Job assistance and placement assistance are support services and should not be interpreted as a guarantee of employment. Success depends on candidate eligibility, performance, and employer requirements.", order: 190 },
  { category: "Jobs", question: "Can freshers apply for jobs through Techwell?", answer: "Yes. Freshers can apply for eligible opportunities listed on the platform. Job listings include specific eligibility criteria; apply only for roles that match your qualifications and experience level.", order: 200 },
  { category: "Jobs", question: "How do I submit my resume?", answer: "You can upload or update your resume through your Techwell profile. Your resume will then be considered for suitable job opportunities shared through the platform. Ensure your profile is complete and up to date.", order: 210 },
  { category: "Jobs", question: "Are the job listings on Techwell verified?", answer: "Techwell works to list legitimate opportunities from verified employers. Techwell will never ask you to pay a fee to apply for a job. Report any suspicious listing to support@techwell.co.in.", order: 220 },
  { category: "Jobs", question: "What types of roles are listed on the platform?", answer: "Roles span a range of IT and technology-related positions, including entry-level, mid-level, and senior roles in software development, networking, cyber security, cloud, AI, IT support, and more.", order: 230 },
  { category: "Jobs", question: "Will I be notified about new job opportunities?", answer: "Yes. Enable job alerts in your Techwell profile settings to receive notifications for new listings that match your skills, preferred location, and job preferences.", order: 240 },

  // ─── Job Assistance ───────────────────────────────────────────────────────
  { category: "Job Assistance", question: "What is job assistance?", answer: "Job assistance is a support service that may include suitable job referrals, resume review, application support, career counselling, interview tips, and guidance throughout the job search process. The specific services available depend on your enrolment plan.", order: 250 },
  { category: "Job Assistance", question: "How does job assistance differ from a job guarantee?", answer: "Job assistance means Techwell supports your job search — we refer you to openings, prepare you for interviews, and guide your applications. A job guarantee would mean Techwell commits to securing employment for you, which we do not offer.", order: 260 },
  { category: "Job Assistance", question: "Does job assistance include resume preparation?", answer: "Yes, depending on the service package, resume review and improvement guidance may be included. Some plans also provide access to Techwell's resume builder tool.", order: 270 },
  { category: "Job Assistance", question: "Will Techwell help me prepare for interviews?", answer: "Yes. Techwell offers interview preparation support including AI-powered mock interviews, feedback reports, common interview question guidance, and tips tailored to your target role and industry.", order: 280 },
  { category: "Job Assistance", question: "How long does job assistance support last?", answer: "The duration of job assistance support varies by plan. Details are specified in your service agreement. Contact support@techwell.co.in for information about your specific plan.", order: 290 },

  // ─── Placement Assistance ─────────────────────────────────────────────────
  { category: "Placement Assistance", question: "What is placement assistance?", answer: "Placement assistance is support provided to help candidates secure employment. It may include job referrals, employer introductions, application coordination, and interview scheduling support. It does not guarantee employment or selection.", order: 300 },
  { category: "Placement Assistance", question: "Who makes the final placement decision?", answer: "The employer or recruiting organisation makes all final decisions regarding candidate selection, salary negotiation, designation, and employment terms. Techwell facilitates the connection but has no authority over these decisions.", order: 310 },
  { category: "Placement Assistance", question: "Is placement assistance available to all students?", answer: "Placement assistance availability depends on the course or plan enrolled in. Check your enrolment details or contact support@techwell.co.in to confirm whether placement support is included in your plan.", order: 320 },
  { category: "Placement Assistance", question: "Can I access placement assistance after completing a course?", answer: "Post-course placement assistance may be available, depending on your plan and the time elapsed since course completion. Speak with your career advisor or contact support for guidance.", order: 330 },
  { category: "Placement Assistance", question: "Does Techwell partner with companies for placements?", answer: "Yes. Techwell maintains relationships with various companies and employers who hire through the platform. These partnerships help connect eligible candidates with relevant job opportunities.", order: 340 },

  // ─── Recruitment ─────────────────────────────────────────────────────────
  { category: "Recruitment", question: "How can employers post jobs on Techwell?", answer: "Employers can register on the Techwell platform and use the employer dashboard to post job openings, search for candidates, and manage applications. Use the Employer Registration link on the website to get started.", order: 350 },
  { category: "Recruitment", question: "Does Techwell offer recruitment services to companies?", answer: "Yes. Techwell provides end-to-end recruitment support including talent sourcing, screening, shortlisting, and candidate referrals to help companies fill technology roles efficiently.", order: 360 },
  { category: "Recruitment", question: "What is the process for hiring candidates through Techwell?", answer: "Employers register on the platform, post a job or submit a recruitment requirement, and Techwell shares suitable candidate profiles. Employers then conduct their own interviews and evaluations before making a hiring decision.", order: 370 },
  { category: "Recruitment", question: "Does Techwell charge candidates for recruitment services?", answer: "No. Techwell does not charge candidates for job placement or recruitment services. If anyone asks you to pay a fee to be placed with a company through Techwell, it is fraudulent. Report it to support@techwell.co.in immediately.", order: 380 },
  { category: "Recruitment", question: "How does Techwell verify candidate profiles?", answer: "Techwell reviews candidate profiles for completeness and authenticity. Employers are also encouraged to conduct their own background checks and verification as part of their hiring process.", order: 390 },
  { category: "Recruitment", question: "Can companies hire in bulk through Techwell?", answer: "Yes. Bulk or volume hiring requirements can be submitted through the campus hiring or consultancy services. Contact us at support@techwell.co.in to discuss large-scale recruitment needs.", order: 400 },

  // ─── Campus Hiring ────────────────────────────────────────────────────────
  { category: "Campus Hiring", question: "What is campus hiring?", answer: "Campus hiring is a recruitment process where companies identify and select eligible students or recent graduates through colleges, universities, or training institutions, before or shortly after they complete their programme.", order: 410 },
  { category: "Campus Hiring", question: "Can colleges conduct campus hiring through Techwell?", answer: "Yes. Colleges and educational institutions can partner with Techwell to facilitate campus hiring drives. Where the service is available, institutions can use Techwell's campus hiring facilities to connect their students with prospective employers.", order: 420 },
  { category: "Campus Hiring", question: "Can companies hire freshers through the campus hiring programme?", answer: "Yes. Companies can use Techwell's campus and recruitment services to identify and hire fresh graduates who meet their eligibility criteria. Employers make all final selection decisions.", order: 430 },
  { category: "Campus Hiring", question: "How does a college register for campus hiring with Techwell?", answer: "Colleges can register by completing the Campus Hiring or Institution Registration enquiry form on the Techwell website. A Techwell representative will get in touch to discuss available services and partnership terms.", order: 440 },
  { category: "Campus Hiring", question: "Are campus hiring events conducted online or on-site?", answer: "Campus hiring events may be conducted online, on-site at the college, or at a Techwell-designated venue, depending on preferences and available facilities. This will be communicated in advance.", order: 450 },
  { category: "Campus Hiring", question: "Is there a fee for colleges to use campus hiring services?", answer: "Fee arrangements for campus hiring partnerships, if applicable, are discussed and agreed upon separately between Techwell and the institution. Contact us at support@techwell.co.in for details.", order: 460 },

  // ─── Payments ─────────────────────────────────────────────────────────────
  { category: "Payments", question: "How should I pay for a Techwell course or service?", answer: "All payments should be made exclusively through the official Techwell payment gateway on the website. Accepted methods include credit/debit cards, net banking, and approved UPI handles. Always verify you are on the official website (techwell.co.in) before making a payment.", order: 470 },
  { category: "Payments", question: "Can I pay directly to an individual?", answer: "No. Never make payments to any individual — even if they claim to be a Techwell representative — outside the official Techwell payment platform. Person-to-person payment requests are a common fraud tactic. If in doubt, verify with support@techwell.co.in before paying.", order: 480 },
  { category: "Payments", question: "Will I receive a receipt or invoice for my payment?", answer: "Yes. For all authorised payments processed through the official Techwell platform, a payment confirmation or official receipt/invoice will be issued. If you do not receive one, contact support@techwell.co.in.", order: 490 },
  { category: "Payments", question: "Are there EMI or instalment payment options available?", answer: "Instalment or EMI payment options may be available for select courses. Details are listed on the relevant course or service page, or can be confirmed by contacting support@techwell.co.in.", order: 500 },
  { category: "Payments", question: "What should I do if my payment fails or is deducted without confirmation?", answer: "Do not attempt another payment immediately. Wait a few minutes and check your email for a confirmation. If no confirmation arrives, contact support@techwell.co.in with your payment transaction reference.", order: 510 },
  { category: "Payments", question: "Is it safe to save my payment details on the Techwell platform?", answer: "Techwell uses industry-standard payment security protocols. Always ensure you are on the official techwell.co.in domain before entering financial information.", order: 520 },

  // ─── Certificates ─────────────────────────────────────────────────────────
  { category: "Certificates", question: "Will I receive a certificate upon completing a course?", answer: "Yes. Upon successful completion of an eligible Techwell course, you will receive a digital completion certificate. Specific eligibility criteria — such as minimum attendance and assessments passed — are outlined in the course details.", order: 530 },
  { category: "Certificates", question: "How do I download my course completion certificate?", answer: "Once your certificate is ready, it will be available in your Techwell dashboard under the Certificates section. Log in to your account, navigate to Certificates, and download your certificate as a PDF.", order: 540 },
  { category: "Certificates", question: "Are Techwell certificates verifiable by employers?", answer: "Yes. Techwell certificates include a unique verification code or QR code that employers can use to verify the authenticity of your certificate online.", order: 550 },
  { category: "Certificates", question: "What if my name or details on the certificate are incorrect?", answer: "If there is an error on your certificate, contact support@techwell.co.in with your enrolment details and the correct information. We will review and reissue the certificate where appropriate.", order: 560 },
  { category: "Certificates", question: "How long does it take to receive my certificate after course completion?", answer: "Certificates are typically issued within 7–10 business days of confirmed course completion and evaluation. If you have not received yours after this period, contact support@techwell.co.in.", order: 570 },
  { category: "Certificates", question: "Is there a fee to reissue a lost or damaged certificate?", answer: "Digital certificates can be re-downloaded from your dashboard at no additional cost. For physical certificates (if issued), a reissuance fee may apply. Contact support@techwell.co.in for assistance.", order: 580 },
  { category: "Certificates", question: "Do Techwell certificates expire?", answer: "Techwell course completion certificates do not expire. However, for industry certifications tied to technology standards, renewal requirements are governed by the relevant certification body — not Techwell.", order: 590 },

  // ─── Consultancy ──────────────────────────────────────────────────────────
  { category: "Consultancy", question: "What consultancy services does Techwell offer?", answer: "Techwell provides technology and business consultancy services including IT strategy, digital transformation guidance, technology implementation advice, cybersecurity assessment, and staffing consultancy. Contact us for a tailored consultation.", order: 600 },
  { category: "Consultancy", question: "Who makes the final hiring or business decision?", answer: "All final decisions — including hiring, selection, salary, designation, and business actions — rest with the employer, client, or relevant decision-making authority. Techwell provides advisory and facilitation services only.", order: 610 },
  { category: "Consultancy", question: "How do I enquire about consultancy services?", answer: "Use the Consultancy enquiry form on the Techwell website, or email support@techwell.co.in with your requirements. A Techwell consultant will get in touch to understand your needs and propose a suitable solution.", order: 620 },
  { category: "Consultancy", question: "Does Techwell sign a formal agreement for consultancy services?", answer: "Yes. Formal consultancy engagements are governed by a written agreement that outlines scope, deliverables, timelines, payment terms, and confidentiality obligations.", order: 630 },
  { category: "Consultancy", question: "Can Techwell help my business with IT infrastructure planning?", answer: "Yes. Techwell consultants can assist with IT infrastructure planning, technology roadmaps, vendor selection, and implementation guidance as part of a customised consultancy engagement. Contact us to discuss your requirements.", order: 640 },

  // ─── Fraud & Safety ───────────────────────────────────────────────────────
  { category: "Fraud & Safety", question: "How can I identify a fake Techwell communication?", answer: "Watch for: unexpected payment requests, payments to personal UPI accounts or bank accounts not linked to Techwell, fake invoices or certificates, offers that seem too good to be true, messages from non-@techwell.co.in addresses, and callers claiming to represent Techwell. Always verify through support@techwell.co.in before acting.", order: 650 },
  { category: "Fraud & Safety", question: "Can AI-generated videos or voices be fake?", answer: "Yes. AI technology can create convincing fake voices, videos (deepfakes), and documents that appear to be from real people or companies, including Techwell. Always verify important or unusual communications through official Techwell channels before making any decisions or payments.", order: 660 },
  { category: "Fraud & Safety", question: "What should I do if I receive a suspicious payment request?", answer: "Do not pay. Do not share your banking details or OTP. Save screenshots of the communication and report it immediately to support@techwell.co.in. You may also report fraud to the Cyber Crime helpline (1930 in India).", order: 670 },
  { category: "Fraud & Safety", question: "Does Techwell ever ask for payment to place me in a job?", answer: "No. Techwell does not charge candidates any fee for job placement, recruitment, or referral. Anyone demanding payment to 'secure' a job on your behalf and claiming to represent Techwell is acting fraudulently.", order: 680 },
  { category: "Fraud & Safety", question: "How do I verify that a Techwell job offer is genuine?", answer: "Verify all job offers by logging into your official Techwell account — genuine offers will be reflected there. Additionally, confirm any offer received externally by emailing support@techwell.co.in with the offer details before accepting or paying anything.", order: 690 },
  { category: "Fraud & Safety", question: "I was scammed by someone claiming to represent Techwell. What should I do?", answer: "Immediately report the incident to support@techwell.co.in with all available evidence (screenshots, transaction details, communication records). You should also file a complaint at your local police station and the Cyber Crime portal (cybercrime.gov.in).", order: 700 },
  { category: "Fraud & Safety", question: "How can I protect myself from phishing attacks targeting Techwell users?", answer: "Only use the official techwell.co.in website. Do not click links in unsolicited emails or messages claiming to be from Techwell. Verify email sender addresses end in @techwell.co.in. Enable two-factor authentication on your Techwell account.", order: 710 },

  // ─── Terms & Conditions ───────────────────────────────────────────────────
  { category: "Terms & Conditions", question: "Where can I read the complete Terms & Conditions?", answer: "The full Terms & Conditions are available via the 'Terms & Conditions' link in the footer of every page on the Techwell website, or directly at /help/terms. Please read them carefully before using our services.", order: 720 },
  { category: "Terms & Conditions", question: "Where can I read the Privacy Policy?", answer: "The Privacy Policy is available via the 'Privacy Policy' link in the footer of every page on the Techwell website, or directly at /help/privacy. It explains how we collect, use, and protect your personal data.", order: 730 },
  { category: "Terms & Conditions", question: "Where can I find the Refund Policy?", answer: "The Refund Policy is available via the 'Refund Policy' link in the website footer, or directly at /help/refund-policy. Please review it before making any payment.", order: 740 },
  { category: "Terms & Conditions", question: "What is Techwell's cookie policy?", answer: "Techwell uses cookies to improve your experience on the platform. The Cookies Policy is available at /help/cookies and explains what cookies are used, their purpose, and how you can manage them.", order: 750 },
  { category: "Terms & Conditions", question: "What is Techwell's AI use policy?", answer: "Techwell's AI Policy governs the use of artificial intelligence tools within the platform. It is available at /help/ai-policy and covers responsible AI use, limitations, and user obligations.", order: 760 },
  { category: "Terms & Conditions", question: "What happens if I violate the Terms & Conditions?", answer: "Violations of the Terms & Conditions may result in suspension or termination of your account and access to Techwell services. In serious cases, Techwell reserves the right to take appropriate legal action.", order: 770 },
  { category: "Terms & Conditions", question: "Do the Terms & Conditions change over time?", answer: "Yes. Techwell may update its Terms & Conditions, Privacy Policy, and other legal documents from time to time. Users will be notified of significant changes. Continued use of the platform constitutes acceptance of the updated terms.", order: 780 },
];

async function seed() {
  console.log('Starting FAQ seed...');

  // Clear existing FAQs to avoid duplicates on re-run
  const deleted = await prisma.faq.deleteMany({});
  console.log(`Cleared ${deleted.count} existing FAQ(s).`);

  // Insert all FAQs
  for (const faq of faqs) {
    await prisma.faq.create({
      data: {
        question: faq.question,
        answer: faq.answer,
        category: faq.category,
        order: faq.order,
        isActive: true,
      },
    });
  }

  console.log(`Successfully seeded ${faqs.length} FAQs across 12 categories.`);
}

seed()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
