import type { Metadata } from 'next'
import Link from 'next/link'
import { FileText, ArrowLeft, Mail } from 'lucide-react'

const BASE_URL = process.env.NEXT_PUBLIC_APP_URL || 'https://techwell.co.in'

export const metadata: Metadata = {
    title: 'Terms of Service | Techwell User Agreement',
    description: 'Techwell Detailed Terms and Conditions for Users.',
    alternates: { canonical: `${BASE_URL}/terms` },
    robots: { index: true, follow: false },
}

export default function TermsPage() {
    return (
        <div className="min-h-screen py-20 bg-background">
            <div className="container max-w-5xl">
                <div className="flex items-center gap-4 mb-8 border-b pb-6">
                    <div className="h-12 w-12 rounded-lg bg-primary/10 flex items-center justify-center">
                        <FileText className="h-6 w-6 text-primary" />
                    </div>
                    <div>
                        <h1 className="text-3xl font-black uppercase tracking-tighter">Terms and Conditions of Service</h1>
                        <p className="text-muted-foreground text-sm font-bold">Effective Date: August 1st, 2026 | Document Reference: TW-LEG-2026-01-B</p>
                    </div>
                </div>

                <div className="bg-muted/10 border border-border p-8 rounded-xl shadow-inner">
                    <div className="text-[10px] leading-tight text-justify text-muted-foreground space-y-4 font-mono">
                        <p className="uppercase font-bold text-foreground">IMPORTANT NOTICE TO ALL USERS: PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY. BY ACCESSING, REGISTERING FOR, OR USING THE TECHWELL PLATFORM, YOU EXPLICITLY AGREE TO BE BOUND BY THESE TERMS AND ALL APPLICABLE LAWS AND REGULATIONS UNDER THE INDIAN CONTRACT ACT, 1872 AND THE INFORMATION TECHNOLOGY ACT, 2000. THESE TERMS ARE DESIGNED TO PROTECT TECHWELL'S BUSINESS INTERESTS.</p>
                        
                        <p><strong>1. ACCEPTANCE OF TERMS AND LEGALLY BINDING AGREEMENT:</strong> This document constitutes a legally binding electronic contract formed under the Information Technology Act, 2000 and rules made thereunder. This electronic record is generated by a computer system and does not require any physical or digital signatures. By clicking "I Agree", "Register", solving the verification captcha, or by continuing to use the platform, you acknowledge that you have read, understood, and accept these Terms in their entirety. If you do not agree, you are expressly prohibited from using our services.</p>

                        <p><strong>2. NON-REFUNDABLE NATURE OF SERVICES AND STRICT DEDUCTIONS:</strong> 
                        Techwell provides educational training, interview preparation, AI tools, and job assistance services. You explicitly agree that <strong>WE WILL NOT PROCESS ANY REFUNDS WHATSOEVER ONCE YOU HAVE ATTENDED ANY LIVE OR RECORDED CLASSES, OR LOGGED INTO THE PORTAL POST-PURCHASE</strong>. The mere provision of educational material, access to learning management systems, and commencement of training constitutes full and final delivery of service for the purpose of refund calculations. Techwell reserves the absolute right to deny any refund request. In the exceptional and sole discretion of Techwell management, if a refund is approved <strong>BEFORE</strong> the utilization of any service (meaning absolutely no classes attended, no materials downloaded, no job assistance used, and no portal logins), such refund shall be strictly subject to the following non-negotiable statutory and administrative deductions: 
                        (a) A deduction of exactly eighteen percent (18%) corresponding to Goods and Services Tax (GST) mandated by the Government of India; 
                        (b) A deduction of two percent (2%) representing our internal administrative, infrastructural, and processing charges; and 
                        (c) A deduction of two percent (2%) representing the non-recoverable Payment Gateway processing charges levied by our third-party financial partners. 
                        Therefore, a total mandatory deduction of twenty-two percent (22%) will be applied to the principal amount paid prior to any partial refund issuance. The user explicitly waives any right to dispute these deductions under the Consumer Protection (E-Commerce) Rules, 2020 or any other applicable statute.</p>

                        <p><strong>3. JOB ASSISTANCE AND PLACEMENT DISCLAIMER:</strong> While Techwell provides "Job Assistance", the user expressly agrees and acknowledges that Techwell does not, under any circumstances, guarantee job placements, specific salary packages, interview clearances, or employment. Job assistance is strictly limited to providing guidance, resume building, and forwarding profiles to partner companies. The final hiring decision rests solely with the third-party employers. Techwell is completely absolved of any liability if a user fails to secure employment. The user agrees not to hold Techwell responsible for their career trajectory, market conditions, or personal interview performance.</p>

                        <p><strong>4. AI SERVICE USAGE AND LIMITATIONS:</strong> Techwell provides AI-driven interview simulations. The user acknowledges that AI is an evolving technology and Techwell makes no representations regarding the 100% accuracy, reliability, or bias-free nature of the AI feedback. Techwell reserves the right to rate-limit, restrict, or completely revoke AI access without prior notice if usage exceeds reasonable boundaries or if server loads require it. The user has no right to demand uninterrupted AI access.</p>

                        <p><strong>5. OWNERSHIP OF USER-GENERATED CONTENT:</strong> By submitting any content, code, interview answers, feedback, or data on the Techwell platform, the user automatically grants Techwell a perpetual, irrevocable, worldwide, royalty-free, and exclusive license to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and display such content in any media. Techwell may use your interview metrics and code submissions for training its AI models without providing any compensation to the user.</p>

                        <p><strong>6. NATURE OF SERVICE AND "AS-IS" PROVISION:</strong> The training, modules, software, platform, and job assistance programs provided by Techwell are provided on a strictly "as-is" and "as-available" basis without warranties of any kind, either express or implied, including, but not limited to, warranties of merchantability, fitness for a particular purpose, or non-infringement. Techwell reserves the unilateral right to modify, suspend, or discontinue any part of the curriculum, service, or platform at any time without prior notice or liability.</p>

                        <p><strong>7. LIMITATION OF LIABILITY:</strong> In no event shall Techwell, its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage, and even if a remedy set forth herein is found to have failed of its essential purpose. The maximum cumulative liability of Techwell, under any and all circumstances, shall never exceed the total amount paid by the user in the thirty (30) days preceding the claim, or INR 1000, whichever is lower.</p>

                        <p><strong>8. INDEMNIFICATION AND HOLD HARMLESS:</strong> You agree to fully and unconditionally defend, indemnify and hold harmless Techwell, its parent companies, licensee and licensors, and their employees, contractors, agents, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees), resulting from or arising out of a) your use and access of the Service; b) a breach of these Terms; c) Content posted on the Service; or d) your violation of any third-party right, including intellectual property or privacy rights.</p>

                        <p><strong>9. RIGHT TO TERMINATE:</strong> Techwell reserves the absolute, unilateral right to suspend, lock, or permanently terminate your account and access to the services at any time, for any reason, without notice or liability. Common reasons for termination include, but are not limited to, sharing account credentials, aggressive behavior towards Techwell staff, attempting to reverse engineer the platform, or violating any clause of these terms. In the event of termination by Techwell, no refunds will be provided.</p>

                        <p><strong>10. FORCE MAJEURE:</strong> Techwell shall not be liable for any failure or delay in performance of its obligations under these Terms arising out of or caused, directly or indirectly, by circumstances beyond its reasonable control, including, without limitation, acts of God, earthquakes, fires, floods, wars, civil or military disturbances, acts of terrorism, sabotage, strikes, epidemics, pandemics, riots, power failures, server crashes, third-party API failures, computer failure and any such circumstances beyond its reasonable control as may cause interruption, loss or malfunction of utility, transportation, computer (hardware or software) or telephone communication service, accidents, labor disputes, acts of civil or military authority, or governmental actions.</p>

                        <p><strong>11. SEVERABILITY AND WAIVER:</strong> If any provision of these Terms is held to be invalid or unenforceable by a court of competent jurisdiction, the remaining provisions of these Terms will remain in full force and effect. These Terms constitute the entire agreement between us regarding our Service. Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights.</p>

                        <p><strong>12. GOVERNING LAW AND DISPUTE RESOLUTION:</strong> These Terms shall be governed and construed exclusively in accordance with the laws of India. Any dispute, controversy, or claim arising out of or relating to this Agreement shall be settled by binding arbitration in accordance with the Arbitration and Conciliation Act, 1996. The seat and venue of arbitration shall be exclusively in Bangalore, Karnataka, India. The user explicitly waives the right to participate in any class action lawsuit against Techwell. The user agrees to bear their own legal costs and half of the arbitration costs.</p>

                        <p><strong>13. INTELLECTUAL PROPERTY RIGHTS:</strong> The Service and its original content, features and functionality are and will remain the exclusive property of Techwell and its licensors. The Service is protected by copyright, trademark, and other laws of India. Users are strictly prohibited from copying, downloading (except where explicitly permitted), screen-recording, distributing, or monetizing any content provided by Techwell. Any violation will result in immediate legal action and a penalty of no less than INR 5,00,000 for damages.</p>

                        <p><strong>14. CHANGES TO TERMS:</strong> Techwell reserves the right, at its sole discretion, to modify or replace these Terms at any time. It is your responsibility to check these Terms periodically for changes. Your continued use of the Service following the posting of any changes to these Terms constitutes strict acceptance of those changes.</p>

                        <p><strong>15. ENTIRE AGREEMENT:</strong> By accepting these terms through the two-step verification process during registration, you confirm that you have read through this entire document, regardless of its length, verbosity, or the size of its text, and you fully, unequivocally, and unconditionally understand and agree to be bound by the non-refundable policies, 22% exceptional deductions, total limitations of liability, job placement disclaimers, and all other clauses stated herein which are heavily in favor of Techwell. This electronic agreement is final, binding, and supersedes any prior oral or written communications.</p>
                    </div>
                </div>

                <div className="mt-8 text-center border-t border-border pt-6">
                    <p className="text-xs text-muted-foreground mb-4">For legal inquiries regarding these terms:</p>
                    <Link href="mailto:info@techwell.co.in">
                        <span className="inline-flex items-center gap-2 text-primary hover:underline text-sm font-bold">
                            <Mail className="h-4 w-4" />
                            info@techwell.co.in
                        </span>
                    </Link>
                    <br /><br />
                    <Link href="/" className="inline-flex items-center gap-2 text-primary hover:underline text-sm">
                        <ArrowLeft className="h-4 w-4" /> Back to Home
                    </Link>
                </div>
            </div>
        </div>
    )
}
