const nodemailer = require('nodemailer');
const axios = require('axios');
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const EMAIL_TARGET = 'techwell.sklm@gmail.com';

// You will configure this via the environment variable or Settings table
// To get this URL, the user creates an Apps Script in their Google Sheet
const GOOGLE_SHEET_WEBHOOK_URL = process.env.GOOGLE_SHEET_WEBHOOK_URL;

/**
 * Configure Nodemailer transport
 */
const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: process.env.SMTP_USER || EMAIL_TARGET,
        pass: process.env.SMTP_PASS // Need an App Password if using Gmail
    }
});

/**
 * Send Email Notification
 */
async function sendLeadEmailNotification(lead) {
    if (!process.env.SMTP_PASS && !process.env.SMTP_USER) {
        console.warn("SMTP credentials not configured. Skipping email notification.");
        return;
    }

    try {
        const mailOptions = {
            from: process.env.SMTP_USER || EMAIL_TARGET,
            to: EMAIL_TARGET,
            subject: `🚨 New Lead/Enquiry: ${lead.name}`,
            html: `
                <h2>New Lead Received</h2>
                <p><strong>Name:</strong> ${lead.name}</p>
                <p><strong>Email:</strong> ${lead.email}</p>
                <p><strong>Phone:</strong> ${lead.phone || 'N/A'}</p>
                <p><strong>Source:</strong> ${lead.source || 'Website'}</p>
                <p><strong>Status:</strong> ${lead.status || 'NEW'}</p>
                <hr/>
                <p><em>This notification was automatically generated by your Techwell System.</em></p>
            `
        };

        await transporter.sendMail(mailOptions);
        console.log("Email notification sent for lead:", lead.id);
    } catch (error) {
        console.error("Failed to send email notification:", error);
    }
}

/**
 * Send Webhook to Google Sheets
 */
async function sendGoogleSheetNotification(lead) {
    let webhookUrl = GOOGLE_SHEET_WEBHOOK_URL;
    
    // If not in ENV, check Settings DB (optional)
    if (!webhookUrl) {
        try {
            const settings = await prisma.institute.findFirst();
            // Assuming you add this to some JSON config field later, or just rely on ENV
        } catch (e) {}
    }

    if (!webhookUrl) {
        console.warn("GOOGLE_SHEET_WEBHOOK_URL is not set. Skipping Sheets sync.");
        return;
    }

    try {
        await axios.post(webhookUrl, {
            id: lead.id,
            name: lead.name,
            email: lead.email,
            phone: lead.phone || '',
            source: lead.source || 'Website',
            status: lead.status || 'NEW',
            createdAt: new Date().toISOString()
        }, {
            headers: { 'Content-Type': 'application/json' }
        });
        console.log("Successfully pushed lead to Google Sheets.");
    } catch (error) {
        console.error("Failed to push lead to Google Sheets:", error);
    }
}

/**
 * Main function to call on new leads
 */
async function notifyNewLead(lead) {
    // Run both asynchronously in the background
    sendLeadEmailNotification(lead).catch(console.error);
    sendGoogleSheetNotification(lead).catch(console.error);
}

module.exports = {
    notifyNewLead
};
